parameters:
#    readroom_categories.example.class: Readroom\CategoriesBundle\Example

services:
#    readroom_categories.example:
#        class: %readroom_categories.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
