parameters:
#    read_room_notifications.example.class: ReadRoom\NotificationsBundle\Example

services:
#    read_room_notifications.example:
#        class: %read_room_notifications.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
