parameters:
#    readroom_user.example.class: Readroom\UserBundle\Example

services:
#    readroom_user.example:
#        class: %readroom_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
