parameters:
#    readroom_books.example.class: Readroom\BooksBundle\Example

services:
#    readroom_books.example:
#        class: %readroom_books.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
